groupName: ovh.solver.hoareau-marion.eu  # Replace with your group name
configVersion: 0.0.2
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

issuers:
  - name: letsencrypt
    create: true
    kind: ClusterIssuer
    acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt.capsule006@simplelogin.com # Replace with your email
    ovhEndpointName: ovh-eu
    ovhAuthenticationMethod: application
    ovhAuthentication:
      existingSecret: ovh-credentials
      keyMap:
        applicationKey: applicationKey
        applicationSecret: applicationSecret
        applicationConsumerKey: consumerKey
