groupName: ovh.solver.hoareau-marion.eu 
configVersion: 0.0.2
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager

issuers:
  - name: letsencrypt
    create: true
    kind: ClusterIssuer
    acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
    email: letsencrypt.capsule006@simplelogin.com # Replace with your email
    ovhEndpointName: ovh-eu
    ovhAuthenticationMethod: application
    ovhAuthenticationRef:
      name: ovh-credentials
      namespace: cert-manager
      # Individual key references inside the secret
      applicationKeyRef:
        name: ovh-credentials
        key: applicationKey
      applicationSecretRef:
        name: ovh-credentials
        key: applicationSecret
      applicationConsumerKeyRef:
        name: ovh-credentials
        key: applicationConsumerKey
